/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static org.eclipse.persistence.platform.database.oracle.plsql.OraclePLSQLTypes.Int;

/**
 *
 * @author adeli
 */
public class ShopMainScreen extends javax.swing.JFrame {

    float valoareCos=0;
     public int showDBInfo() throws SQLException 
    {
        // lets read specific row on the database
        Connection con = DbConnectionAccountsDatabase.connect(); 
        DefaultTableModel tab;
        tab = (DefaultTableModel) tabelProduse.getModel();
        tab.setRowCount(0);
        PreparedStatement ps = null; 
        ResultSet rs = null; 
        
        String denum;
        String ingr;
        String pret;
     
        try 
        {
            String sql = "Select Denumire,Ingrediente,Pret from Produse ORDER BY Denumire";  // Selecteaza utilizatorii din BD
            ps = con.prepareStatement(sql); 
            rs = ps.executeQuery(); 
    
            while(rs.next())
            {
                // we are reading one row, so no need to loop 
               denum = rs.getString(1); 
                ingr = rs.getString(2);
                pret = rs.getString(3);
        
                String []infoTabel={denum,ingr,pret};
tab.addRow(infoTabel);
            }
        }
        catch(SQLException e) 
        {
            System.out.println(e.toString());
        } 
        finally 
        {
            // close connections
            try
            {
                rs.close(); 
                ps.close();
                con.close(); 
            } 
            catch (SQLException e) 
            {
                // TODO: handle exception
                System.out.println(e.toString());
            }
        }
        return 0;
    }    
      
    
    
    
    /** Creates new form ShopMainScreen */
    public ShopMainScreen() throws SQLException {
        initComponents();
        showDBInfo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduse = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelCos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        InfoDetText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valCos = new javax.swing.JLabel();
        listaCantitate = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(875, 545));
        setPreferredSize(new java.awt.Dimension(865, 575));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelProduse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Denumire", "Ingrediente", "Pret /  kg"
            }
        ));
        tabelProduse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProduseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelProduse);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 500, 230));

        tabelCos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Denumire", "Pret"
            }
        ));
        jScrollPane2.setViewportView(tabelCos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 320, 230));

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produse disponibile");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 390, -1));

        jLabel2.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cos cumparaturi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jButton1.setText("Adauga in cos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 40));

        jButton2.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jButton2.setText("Sterge");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 110, 40));

        jButton3.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jButton3.setText("Finalizare comanda");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, 40));

        InfoDetText.setColumns(20);
        InfoDetText.setLineWrap(true);
        InfoDetText.setRows(5);
        jScrollPane3.setViewportView(InfoDetText);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 500, 140));

        jLabel3.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jLabel3.setText("Kg");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 50, 40));

        jLabel4.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valoare Cos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 180, 30));

        valCos.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 36)); // NOI18N
        valCos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valCos.setText("0.00");
        getContentPane().add(valCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 240, 100));

        listaCantitate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5" }));
        getContentPane().add(listaCantitate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 50, 40));

        jLabel5.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jLabel5.setText("Detalii");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 30));

        jLabel6.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jLabel6.setText("Cantitate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelProduseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProduseMouseClicked
        // TODO add your handling code here:
        
                                         
        // TODO add your handling code here:
        String InfoDet="";
        int column = 0;
int row = tabelProduse.getSelectedRow();
for(int i=0;i<=2;i++)
{
    String value = tabelProduse.getModel().getValueAt(row,i).toString();
        if(i==0)InfoDet+="Denumire Produs: "+value+"\n\n";
        if(i==1)InfoDet+="Ingrediente: "+value+"\n\n";
        if(i==2)InfoDet+="Pret (lei) : "+value+"\n\n";
       
}
        
InfoDetText.setText(InfoDet);

                                           
    }//GEN-LAST:event_tabelProduseMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tab;
         tab = (DefaultTableModel) tabelCos.getModel();
        int column = 0;
        String cantitate;
int row = tabelProduse.getSelectedRow();

    String col1 = tabelProduse.getModel().getValueAt(row,0).toString();
    String col2 = tabelProduse.getModel().getValueAt(row,1).toString();
    String col3 = tabelProduse.getModel().getValueAt(row,2).toString();
       cantitate=listaCantitate.getSelectedItem().toString();
       col3=String.valueOf(Float.parseFloat(cantitate)*Integer.parseInt(col3));
    String []addToTable={col1,col3};
 
       tab.addRow(addToTable);
       
       
valoareCos+=Float.parseFloat(col3);
valCos.setText(String.valueOf(valoareCos)+" lei");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Denumire="";
        String pretDeSters="0";
      DefaultTableModel tab;
      tab= (DefaultTableModel) tabelCos.getModel();
        int input=0;
        int row = tabelCos.getSelectedRow();
        System.out.println("rand"+row);
        if(row!=-1)
        {
            Denumire=(String) tabelCos.getModel().getValueAt(row,0);
            pretDeSters=(String) tabelCos.getModel().getValueAt(row,1);
        }
        
        if(row!=-1)input = JOptionPane.showConfirmDialog(null, 
                "Esti sigur ca vrei sa stergi "+Denumire, "Selecteaza optiune...",JOptionPane.YES_NO_CANCEL_OPTION);
        //System.out.println("input "+input);
        if(row!=-1){
            if(input!=1&&input!=2&&input!=-1)
            {
                
                tab.removeRow(row);
                valoareCos=valoareCos-Float.parseFloat(pretDeSters);
                valCos.setText(String.valueOf(valoareCos));
                InfoDetText.setText("");
                
            }
            //System.out.println("DELETE APELAT");
        
        try {
            showDBInfo();
        }   catch (SQLException ex) { 
                Logger.getLogger(ShopMainScreen.class.getName()).log(Level.SEVERE, null, ex);
            } 
        
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShopMainScreen().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ShopMainScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea InfoDetText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> listaCantitate;
    private javax.swing.JTable tabelCos;
    private javax.swing.JTable tabelProduse;
    private javax.swing.JLabel valCos;
    // End of variables declaration//GEN-END:variables

}
